apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-maker
  labels:
    app: test-maker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-maker
  template:
    metadata:
      labels:
        app: test-maker
    spec:
      containers:
      - name: test-maker
        image: test-maker:v1
        ports:
        - containerPort: 5000