apiVersion: v1
kind: Service
metadata:
  name: test-maker-service
spec:
  selector:
    app: test-maker
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
  type: NodePort